services:
 api:
  build: .
  container_name: hr-managment-api
  ports:
   - "3001:3001"
  env_file:
   - hr-api/.env
  depends_on:
   - postgres
  restart: always
 postgres:
  image: postgres:16-alpine
  container_name: postgres
  environment:
   POSTGRES_DB: hr_api
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  volumes:
   - pgdata:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  restart: always

volumes:
 pgdata:
